on: 
  workflow_dispatch:
jobs:
  run_acceptance_tests:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'ok-to-test')
    steps:
    - run: |
        echo "sausage"
